---
brew_taps:
  - homebrew/cask-versions
  - homebrew/cask-fonts

brew_packages:
  - ansible
  - docker
  - fnm
  - mas
  - pnpm
  - zplug
  - yarn

cask_packages:
  # applications
  - 1password
  - arc
  - bartender
  - discord
  - firefox
  - notion
  - rectangle
  - raycast
  - slack
  - spotify
  - zoom
  # development
  - figma
  - insomnia
  - iterm2
  - sourcetree
  - tableplus
  - viscosity
  - visual-studio-code
  # fonts
  - font-meslo-lg-nerd-font
  - font-jetbrains-mono-nerd-font

mas_packages:
  - 937984704 # amphetamine
  - 418412301 # clean
  - 430798174 # hazeover

vscode_packages:
  - aaravb.chrome-extension-developer-tools
  - aaron-bond.better-comments
  - astro-build.astro-vscode
  - bradlc.vscode-tailwindcss
  - Catppuccin.catppuccin-vsc
  - DaltonMenezes.aura-theme
  - dbaeumer.vscode-eslint
  - dkundel.vscode-new-file
  - dsznajder.es7-react-js-snippets
  - eamodio.gitlens
  - esbenp.prettier-vscode
  - fabiospampinato.vscode-todo-plus
  - formulahendry.auto-close-tag
  - formulahendry.auto-rename-tag
  - GitHub.copilot
  - Gruntfuggly.todo-tree
  - kisstkondoros.vscode-codemetrics
  - lllllllqw.jsdoc
  - mariusschulz.yarn-lock-syntax
  - mikestead.dotenv
  - ms-azuretools.vscode-docker
  - ms-vscode-remote.remote-containers
  - ms-vscode.atom-keybindings
  - ms-vscode.makefile-tools
  - naumovs.color-highlight
  - Prisma.prisma
  - sleistner.vscode-fileutils
  - solidjs-community.solid-snippets
  - tamasfe.even-better-toml
  - ue.alphabetical-sorter
  - vscodevim.vim
  - wayou.vscode-todo-highlight
  - wengerk.highlight-bad-chars
  - wix.vscode-import-cost
  - xabikos.JavaScriptSnippets
  - xdae.vscode-snazzy-theme
  - Zignd.html-css-class-completion

node_versions:
  - latest
  - 18.06
