---
- name: Setup dotfiles
  hosts: local

  vars_files: ["config.packages.yml"]

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ["brew"]

    - role: brew
      tags: ["brew"]

    - role: zsh
      tags: ["zsh"]

    - role: dotfiles
      tags: ["dotfiles"]

    - role: git
      tags: ["git"]

    - role: iterm
      tags: ["iterm"]

    - role: fnm
      tags: ["fnm"]

    - role: nvim
      tags: ["nvim"]

    - role: tmux
      tags: ["tmux"]

    - role: mas
      tags: ["mas"]

    - role: vscode
      tags: ["vscode"]

    - role: osx
      tags: ["osx"]
