---
brew_taps:
  - homebrew/cask-versions
  - homebrew/cask-fonts

brew_packages:
  - ansible
  - exa
  - fnm
  - go
  - golangci-lint
  - mas
  - neovim
  - pnpm
  - ripgrep
  - tmux
  - wget
  - yarn
  - zplug

cask_packages:
  # applications
  - 1password
  - arc
  - bartender
  - backblaze
  - discord
  - firefox
  - notion
  - rectangle
  - raycast
  - slack
  - spotify
  - zoom
  # development
  - figma
  - insomnia
  - iterm2
  - openvpn-connect
  - sourcetree
  - tableplus
  - visual-studio-code
  # fonts
  - font-meslo-lg-nerd-font
  - font-jetbrains-mono-nerd-font

mas_packages:
  - 937984704 # amphetamine
  - 418412301 # clean
  - 430798174 # hazeover

vscode_packages:
  - aaron-bond.better-comments
  - alefragnani.project-manager
  - astro-build.astro-vscode
  - bradlc.vscode-tailwindcss
  - Catppuccin.catppuccin-vsc
  - Catppuccin.catppuccin-vsc-icons
  - dbaeumer.vscode-eslint
  - eamodio.gitlens
  - esbenp.prettier-vscode
  - golang.go
  - letrieu.expand-region
  - lllllllqw.jsdoc
  - mariusschulz.yarn-lock-syntax
  - mattpocock.ts-error-translator
  - meganrogge.template-string-converter
  - mikestead.dotenv
  - ms-azuretools.vscode-docker
  - ms-python.python
  - ms-vscode-remote.remote-containers
  - ms-vscode.makefile-tools
  - naumovs.color-highlight
  - Orta.vscode-twoslash-queries
  - Prisma.prisma
  - svelte.svelte-vscode
  - tamasfe.even-better-toml
  - tobias-z.vscode-harpoon
  - usernamehw.errorlens
  - vscodevim.vim
  - VSpaceCode.whichkey
  - wayou.vscode-todo-highlight
  - wengerk.highlight-bad-chars
  - yoavbls.pretty-ts-errors
  - Zignd.html-css-class-completion

node_versions:
  - 18.06
  - 20.0.0
