---
# - name: "[ vscode ] Get list of vscode extensions"
#   command: cat ~/Development/dotfiles/files/vscode/extensions.txt
#   register: result

# - name: "[ vscode ] Install vscode extensions"
#   package: "code --install-extension {{ item }} --force"
#   loop: "{{ result.stdout_lines }}"
- name: "[ vscode ] Install extensions"
  vscode:
    name: "{{ item }}"
  loop: "{{ vscode_extensions }}"

- name: "[ vscode ] Set symlink to vscode settings"
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/files/vscode/settings.json"
    path: "~/Library/Application\ Support/Code/User/settings.json"
    state: link
    force: yes
