---
- name: "[ vscode ] Install extensions"
  ansible.builtin.shell: SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"; cat ${SCRIPTPATH}/files/vscode/extensions.txt | while read extension; do code --install-extension $extension; done
