---
- name: "[ vscode ] Install extensions"
  shell: |
    cat ~/Development/dotfiles/files/vscode/extensions.txt | while read extension; do code --install-extension $extension --force; done

- name: "[ vscode ] Update settings"
  shell: |
    cp ~/Development/dotfiles/files/vscode/settings.json ~/Library/Application\ Support/Code/User/settings.json
