---
- name: "[ zsh ] Run pre-install clean up"
  shell: rm -rf ~/.oh-my-zsh ~/.zshrc 

- name: "[ zsh ] Install oh-my-zsh"
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- name: "[ zsh ] Install Starship"
  shell: brew install starship

- name: "[ zsh ] Link .zshrc"
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/zsh/files/.zshrc"
    path: "~/.zshrc"
    state: link
    force: yes

- name: "[ zsh ] Link starship.toml"
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/zsh/files/starship.toml"
    path: "~/.config/starship.toml"
    state: link
    force: yes

- name: "[ zsh ] Restart zsh"
  shell: exec zsh
