---
- name: "[ zsh ] Run pre-install clean up"
  shell: rm -rf ~/.oh-my-zsh ~/.zshrc 

- name: "[ zsh ] Install oh-my-zsh"
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- name: "[ zsh ] Install Starship"
  shell: brew install starship

- name: "[ zsh ] Source powerlevel10k"
  shell: echo "eval \"$(starship init zsh)\"" >>~/.zshrc

- name: "[ zsh ] Restart zsh"
  shell: exec zsh
