---
- name: "[ git ] Link root config"
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/git/files/.gitconfig"
    path: "~/.gitconfig"
    state: link
    force: yes

- name: "[ git ] Create config directory"
  ansible.builtin.file:
    path: "~/.config/git"
    state: directory
    mode: "0755"

- name: "[ git ] Link config profiles"
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/git/files/git"
    dest: "~/.config/git"
    state: link
    force: yes
