---
- name: "[ git ] Move .gitconfig"
  ansible.builtin.copy:
    src: "{{ ansible_env.PWD }}/roles/git/files/.gitconfig"
    dest: "~/.gitconfig"
    force: yes

- name: "[ git ] Move .gitconfig (personal)"
  ansible.builtin.copy:
    src: "{{ ansible_env.PWD }}/roles/git/files/personal/.gitconfig"
    dest: "~/Development/personal/.gitconfig"
    force: yes

- name: "[ git ] Move .gitconfig (work)"
  ansible.builtin.copy:
    src: "{{ ansible_env.PWD }}/roles/git/files/work/.gitconfig"
    dest: "~/Development/work/.gitconfig"
    force: yes