---
- name: "[ tmux ] Create preferences directory"
  ansible.builtin.file:
    path: "~/.config/tmux"
    state: directory
    mode: "0755"

- name: "[ tmux ] Link preferences"
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/tmux/files/tmux"
    path: "~/.config/tmux"
    state: link
    force: yes

- name: "[ tmux ] Install tpm"
  ansible.builtin.command: git clone https://github.com/tmux-plugins/tpm {{ ansible_env.PWD }}/roles/tmux/files/tmux/plugins/tpm
