---
- name: "[ osx ] Set ComputerName"
  osx_defaults:
    domain: scutil
    key: ComputerName
    type: string
    value: "0x6969766f"
    state: present

- name: "[ osx ] Set HostName"
  osx_defaults:
    domain: scutil
    key: HostName
    type: string
    value: "0x6969766f"
    state: present

- name: "[ osx ] Set LocalHostName"
  osx_defaults:
    domain: scutil
    key: LocalHostName
    type: string
    value: "0x6969766f"
    state: present

- name: "[ osx ] Set NetBIOSName"
  osx_defaults:
    domain: ~/Library/Preferences/SystemConfiguration/com.apple.smb.server
    key: NetBIOSName
    type: string
    value: "0x6969766f"
    state: present

- name: "[ osx ] Disable boot sound"
  osx_defaults:
    domain: nvram
    key: SystemAudioVolume
    type: string
    value: " "
    state: present

- name: "[ osx ] Expand save panel by default"
  osx_defaults:
    domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: true
    state: present

- name: "[ osx ] Expand print panel by default"
  osx_defaults:
    domain: NSGlobalDomain
    key: PMPrintingExpandedStateForPrint
    type: bool
    value: true
    state: present

- name: "[ osx ] Automatically quit printer app once the print jobs complete"
  osx_defaults:
    domain: com.apple.print.PrintingPrefs
    key: "Quit When Finished"
    type: bool
    value: true
    state: present

- name: "[ osx ] Save to disk (not to iCloud) by default"
  osx_defaults:
    domain: NSGlobalDomain
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: false
    state: present

- name: "[ osx ] Enable tap to click"
  osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    type: bool
    value: true
    state: present

- name: "[ osx ] Increase sound quality for Bluetooth headphones/headsets"
  osx_defaults:
    domain: com.apple.BluetoothAudioAgent
    key: "Apple Bitpool Min (editable)"
    type: int
    value: 40
    state: present

- name: "[ osx ] Require password immediately after sleep or screen saver begins"
  osx_defaults:
    domain: com.apple.screensaver
    key: askForPassword
    type: int
    value: 1
    state: present

- name: "[ osx ] Set require password window delay to 0"
  osx_defaults:
    domain: com.apple.screensaver
    key: askForPasswordDelay
    type: int
    value: 0
    state: present

- name: "[ osx ] Set custom screenshot directory"
  osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: "~/${HOME}/Screenshots"
    state: present
