---
- name: "[ iterm ] Link preferences"
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/iterm/files/com.googlecode.iterm2.plist"
    path: "~/.config/iterm2/com.googlecode.iterm2.plist"
    state: link
    force: yes

- name: "[ iterm ] Link themes"
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/iterm/files/themes"
    path: "~/.config/iterm2/themes"
    state: link
    force: yes

- name: "[ iterm ] Set custom preferences directory"
  osx_defaults:
    domain: com.googlecode.iterm2
    key: PrefsCustomFolder
    type: string
    value: "~/.config/iterm2"
    state: present

- name: "[ iterm ] Enable custom preference"
  osx_defaults:
    domain: com.googlecode.iterm2
    key: LoadPrefsFromCustomFolder
    type: bool
    value: true
    state: present
